#!/usr/bin/env python
# coding: utf-8



import json
import openai
from tqdm import tqdm
import random
import time
from datasets import load_dataset,concatenate_datasets

openai.api_key = 'your_api_key'




The rating for this feedback is:




def get_teacher_advice(response):
    advice=""
    for i in range(1,5):
        try:
            tmp=response.split(f"[Teacher's explanations and advice {i}] :")[1].split(f"[Wrong")[0]
            advice+=tmp

        except:
            if advice !='':
                return advice
            if "**Teacher's explanations and advice:**" in response:
                advice+=response.split("**Teacher's explanations and advice:**")[1]
            elif "**Teacher's explanations and advice**:" in response:
                advice+=response.split("**Teacher's explanations and advice**:")[1]
            elif r"**\[Teacher's Explanations and Advice\]:**" in response:
                advice+=response.split(r"**\[Teacher's Explanations and Advice\]:**")[1]
            elif "**Teacher's explanations and advice:]**" in response:
                advice+=response.split("**Teacher's explanations and advice:]**")[1]
            elif "**Teacher's Explanations and Advice:**" in response:
                advice+=response.split("**Teacher's Explanations and Advice:**")[1]
            elif "**[Teacher's explanations and advice 1]:**" in response:
                advice+=response.split("**[Teacher's explanations and advice 1]:**")[1]
            elif "**[Teacher's explanations and advice 1]**:" in response:
                advice+=response.split("**[Teacher's explanations and advice 1]**:")[1]
            elif "**[Teacher's Explanations and Advice]**" in response:
                advice+=response.split("**[Teacher's Explanations and Advice]**")[1] 
            elif "**[Teacher's Explanations and Advice]:**" in response:
                advice+=response.split("**[Teacher's Explanations and Advice]:**")[1]
            elif "**Explanation:**" in response:
                advice+=response.split("**Explanation:**")[1]
            elif "[Teacher's Explanations and Advice]:**" in response:
                advice+=response.split("[Teacher's Explanations and Advice]:**")[1]
            elif "[Teacher's Explanations and Advice]**:" in response:
                advice+=response.split("[Teacher's Explanations and Advice]**:")[1]
            elif "[Teacher's explanations and advice ] :" in response:
                advice+=response.split("[Teacher's explanations and advice ] :")[1]
            elif r"[Teacher's Explanations and Advice\]:**" in response:
                advice+=response.split(r"[Teacher's Explanations and Advice\]:**")[1]    
            
            elif "**Explanation of the Mistake:**" in response:
                advice+=response.split("**Explanation of the Mistake:**")[1]
            elif "[Teacher's explanations and advice 1]**:" in response:
                advice+=response.split("[Teacher's explanations and advice 1]**:")[1]
                
            elif "[Teacher's explanations and advice 1]:**" in response:
                advice+=response.split("[Teacher's explanations and advice 1]:**")[1]
            elif "[Teacher's explanations and advice 1]:**" in response:
                advice+=response.split("[Teacher's explanations and advice 1]:**")[1]
                  
            elif "[Teacher's Explanations and Advice]**" in response:
                advice+=response.split("[Teacher's Explanations and Advice]**")[1]
            elif "[Teacher's explanations and advice]" in response:
                advice+=response.split("[Teacher's explanations and advice]")[1]
            return advice
            
    return advice




def create_prompt(groundtruth,response):
    prompt=[]
    gt_teacher=''
    prompt.append({"role": "system","content":"Given a problem, student's process and the teacher's manual suggestions, please rate the following suggestions generated by different models on a scale from 0 to 5. The criteria for the rating are: 0: Completely irrelevant or nonsensical suggestions. 1: Very poor suggestions with little relevance or helpfulness. 2: Poor suggestions with some relevance but mostly unhelpful. 3: Average suggestions that are somewhat relevant and somewhat helpful. 4: Good suggestions that are relevant and helpful but could be improved. 5: Excellent suggestions that are highly relevant, helpful, and well-aligned with the teacher's manual suggestions. Please only answer in the following format: The rating for this feedback is :"})
    for error in groundtruth['teacher_review']['error']:
        gt_teacher+=error['teacher_advice_en']
    user_prompt=''
    user_prompt+=f"[Problem] : {groundtruth['Problem']} [Student process] : {groundtruth['student_process']} [Teacher's manual suggestions] : {gt_teacher} "
    user_prompt+=f"[Model] : {response} "
    prompt.append({"role": "user","content":user_prompt})
    return prompt




##time series split




score_list=[]
count=0
for i,data in tqdm(enumerate(o1_mini_woR)):
    if data['correct_or_not']=='wrong':
        count+=1
        response = data['gpt_o1_mini_response']
        if judge(response)==1:
            score_list.append(0)
        else:
            try:
                if "Teacher's explanations and advice" in response:
                    advice = response.split("Teacher's explanations and advice")[1]
                elif "Teacher's Explanations and Advice" in response:
                    advice = response.split("Teacher's Explanations and Advice")[1]
            except:
                print(response)
                score_list.append(0)
                continue
            prompt=create_prompt(data,[advice]) 
            chat_completion = client.chat.completions.create(
                messages=prompt,
                model="llama3-70b-8192",
                temperature=0
            )
            time.sleep(2)
            score_list.append(chat_completion.choices[0].message.content)
            




with open('model_response/time_series_split_feedback_generation.json', 'r') as f:
    responses=json.load(f)

score_dic = {}
count=0

for key, value in responses[0].items():
    if 'wr' not in key and 'wor' not in key:
        continue
    else:
        # [ground turth wrong amount, em count, dis sum]
        score_dic[key]=0

for dic in responses:
    if dic['correct_or_not']=='wrong':
        count+=1
    for key,value in dic.items():
        if 'wr' not in key and 'wor' not in key:
            continue
        else:
            if dic['correct_or_not']=='wrong':
                    score_dic[key][1]+=1
                    if value.strip()!='' and value!="The student's answer is correct and doesn't need advice." :
                        feed_back = get_teacher_advice(value)
                        if feed_back!='':
                            prompt=create_prompt(dic,data,feed_back) 
                            response = openai.ChatCompletion.create(
                                        model="gpt-4-turbo",
                                        messages=prompt,
                                        temperature=0 
                            )
                            response["choices"][0]['message']['content']
                            try:
                                score_dic[key]+=int((response["choices"][0]['message']['content'].split('The rating for this feedback is :')[1].strip())
                            except
                                score_dic[key]+=0
                        else:
                            score_dic[key]+=0
                    else:
                        score_dic[key]+=0

for key,value in score_dic.items():
    print(key)
    print(f'LLM Rating : {value/count}')
    print()

